---
name: mvn
on: [push]
jobs:
  mvn:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        java: [11, 17]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@93287a1fa82c6ddbb6d8db978df4b0119cd8879f
        with:
          ruby-version: '3.1'
      - run: java -version
      - run: mvn -version
      - run: npm install -g eolang@0.10.0
      - run: gem install xcop
      - run: mvn --errors --batch-mode clean install -Pqulice